### PR TITLE
Allow signing of empty data for SmartKey

### PR DESCRIPTION
**Pull request by rchaing-figure**
Let SmartKey sign empty data, mirror what the java Signature class currently does, cause there are uses cases where data comes in as empty but still gets signed.

### CODE REVIEW

**Comment by scirner22** [comment]
Were you able to replicate the problem we were seeing? I guess it would be a contract where you propose multiple facts and make one of them an empty proto, then hydrate.

**Comment by scirner22** [comment]
Also curious if each singing instance is totally separate, how does one empty proto cause the others in the record group to sign incorrectly?

**Comment by rchaing-figure** [comment]
This might be the case of hash and p8e-contract versions coming from different time spans, with the invalid signature.

Just ran this against SynergyOne on Test with it being SmartKey type, and it executed successfully.

**Comment by rchaing-figure** [comment]
This just allows signing of empty protos to be signed, different from the unable to verify signatures cases that have been floating about.

**Review by scirner22 — APPROVED** [review]

**Pull request merged**
